version: '3.8'
services:
  # Serviço para a API NestJS
  api:
    build: ./my-nest-crud
    ports:
      - "3000:3000" # Porta onde a API estará rodando
    environment:
      - JWT_SECRET=yourSecretKey
      - MONGO_URI=mongodb://root:password@mongo:27017/mydb?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

  # Serviço para o MongoDB
  mongo:
    image: mongo:latest
    container_name: book-crud-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network
    restart: always

  # Serviço para o front-end Angular
  front:
    build: ./my-angular-crud
    ports:
      - "4200:4200"  # Mapeia a porta 4200 do host para a porta 4200 do container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Isso é necessário para rodar o Angular corretamente no Docker em alguns sistemas
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
